domains = { "example.net", "example.com", add-your-domains-here }
srs-domain = "srs.example.net"
secrets-file = "/etc/postsrsd/secrets/list"
socketmap = inet:0.0.0.0:10003
unprivileged-user = ""
chroot-dir = ""
